# Generated by Django 3.2 on 2021-05-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210504_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='diary',
        ),
        migrations.AddField(
            model_name='diary',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary', to='home.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(related_name='students', to='home.Project'),
        ),
    ]
