# Generated by Django 3.2 on 2021-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_project_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
