# Generated by Django 3.2 on 2021-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210508_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicband',
            name='alb',
            field=models.ManyToManyField(related_name='album', to='home.Album'),
        ),
    ]
